[tool.poetry]
name = "nflapp"
version = "0.1.0"
description = ""
authors = ["Jason Walsh <j@wal.sh>"]

[tool.poetry.dependencies]
python = "^3.10"
files-to-prompt = "^0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
